services:
  web:
    build:
      context: ./
    expose:
      - "8000"  
    # depends_on:
    #   - db

  # db:
  #   image: nouchka/sqlite3  # Example database; replace as needed
  #   volumes:
  #     - ./data:/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - "8080:80"  
    depends_on:
      - web
